### ISSUE TITLE
Make timeout of subprocesses a config setting

### ISSUE THREAD

**Issue by fw8** [geospin-takelage/takelage-dev#3]
Sometimes it could happen, that the subprocess used in takelage.py takes longer then the hardcoded value of 10 seconds.
It would be nice, to be able to change this value on demand.

**Comment by stephan-devop** [comment]
This is a „won't fix". The scripts only checks if the takelage core functionality is available. The only reason for the timeout is that the script should terminate if one of the programs (gpg, gopass, ...) hangs.
